name: Testing github action for devops

on:
  push:
    branches:
      - devops
jobs:
  build-odysseygo:
    name: Build Odysseygo binary
    runs-on: ubuntu-latest
    env:
      ARCH: "amd64"
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-deps

      - uses: ./.github/actions/setup-go

      - name: Build Binary
        run: |
          ./scripts/build.sh
        shell: bash

      - name: Archive binary in Targz
        run: |
          cd build
          tar -czvf ../odysseygo-linux-amd64-test.tar.gz odysseygo
        shell: bash

      - name: Upload artifact with odysseygo
        uses: actions/upload-artifact@v4
        with:
          name: odysseygo-linux-amd64-test
          path: odysseygo-linux-amd64-test.tar.gz
          retention-days: 30
